 - hosts: all
   tasks:
     - name: Install dependencies
       package:
         name:
           - 'jq'
           - 'just'
           - 'ostree'
           - 'python3-pyyaml'
           - 'rpm-ostree'
           - 'selinux-policy-targeted'
         state: present
       become: yes
     - name: Compose the base variant
       ansible.builtin.command:
         chdir: "{{ zuul.project.src_dir }}"
         cmd: just compose-legacy base
